import os
import datetime
from mcp.server.fastmcp import FastMCP
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from dotenv import load_dotenv

load_dotenv()

mcp = FastMCP("Google Calendar")
SCOPES = ['https://www.googleapis.com/auth/calendar.events']

def get_calendar_service():
    if not os.path.exists('token.json'):
        raise Exception("token.json not found. Please run authenticate_calendar.py first.")
    
    creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    service = build('calendar', 'v3', credentials=creds)
    return service

@mcp.tool()
def create_calendar_event(
    title: str,
    date: str,
    description: str,
) -> str:
    """
    Creates an event in the user's Google Calendar.
    Requires token.json generated by authenticate_calendar.py.
    
    Args:
        title: The title of the event
        date: The date/time in ISO format (e.g. '2026-09-22T09:00:00Z')
        description: Description of the event
    """
    try:
        service = get_calendar_service()
        
        # Determine end time (assume 1 hour duration for tasks/treatments)
        start_time = datetime.datetime.fromisoformat(date.replace('Z', '+00:00'))
        end_time = start_time + datetime.timedelta(hours=1)
        
        event = {
          'summary': title,
          'description': description,
          'start': {
            'dateTime': start_time.isoformat(),
          },
          'end': {
            'dateTime': end_time.isoformat(),
          },
        }
        
        event = service.events().insert(calendarId='primary', body=event).execute()
        return f"Successfully created event '{title}'. Event ID: {event.get('id')}"
        
    except Exception as e:
        return f"Error creating calendar event: {str(e)}"

if __name__ == "__main__":
    mcp.run()
